version: '3.8'

services:
  rd_web_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rd_web_backend
    restart: always
    ports:
      - "8000:8000"

  rd_web_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rd_web_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - rd_web_backend
